services:
  treenodeapp:
    container_name: 'treenode.app'
    image: aschebet.treenode
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/cert/aschebet.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=aschebet
    build:
      context: .
      dockerfile: AShebetTreeNode.Server\Dockerfile
    ports:
      - 8080:5000
      - 8081:5001
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - "postgres"
    networks:
      - treenode-network
  postgres:
    container_name: 'treenode.db'
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: treenodedb
    networks:
      - treenode-network
  pgadmin:
    container_name: 'treenode.pgadmin'
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 3000:80
    depends_on:
      - "postgres"
    networks:
      - treenode-network  
networks:
  treenode-network:
     driver: bridge